name: Publish
on:
    push:
        tags:
            - '*.*.*'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '9.x'
            - name: Restore dependencies
              run: dotnet restore UuidGen.sln
              working-directory: src
            - name: Build
              run: dotnet build UuidGen.sln -c Release --no-restore
              working-directory: src
            - name: Pack
              run: dotnet pack UuidGen.sln -c Release --no-build -o ./nupkg /p:PackageVersion=${{ github.ref }}
              working-directory: src
            - name: Publish
              env:
                  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
              run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
              working-directory: src